name: Go Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.11", "1.17", "1.20"]
    steps:
      - name: Setup G
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version