name: Output
on: push
env:
  MONGODB_DB_NAME: MY_DB
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_USERNAME: MY_USERNAME
      PORT: 8080
    steps:
      - run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
          echo "PORT: $PORT"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
          echo "PORT: $PORT"