on: push
env:
  ENV1: VAL1
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_ACTION
        name: Hello!
        id: my_id
      - name: env
        run: echo "${{ toJSON(env) }}"
      - run: echo "${{ toJSON(github) }}"